export const ADD_USER_TO_STATE = 'ADD_USER_TO_STATE';
export const REMOVE_USER_FROM_STATE = 'REMOVE_USER_FROM_STATE';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_CV_TEMPLATE='UPDATE_CV_TEMPLATE';
export const UPDATE_CL_TEMPLATE='UPDATE_CL_TEMPLATE';
